language: go

cache:
  directories:
  - $HOME/opus
  - $HOME/bin
  - $TRAVIS_BUILD_DIR/.vendor

before_script:
    - export PATH=$PATH:~/bin/
    - export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$HOME/opus/lib/pkgconfig
    - bash install-dependencies.sh

install:
    - ls -R $HOME/opus