language: go

cache:
  directories:
  - $HOME/opus
  - $HOME/bin
  - $GOPATH/bin
  - $GOPATH/pkg
  - $GOPATH/src/github.com/nitrous-io
  - $GOPATH/src/github.com/MichaelOultram/mumbledj/.vendor

before_script:
    - export PATH=$PATH:~/bin/
    - export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$HOME/opus/lib/pkgconfig
    - bash install-dependencies.sh

install:
    - ls -R $HOME/opus