language: go

cache:
  directories:
  - $HOME/opus
  - $HOME/bin
  - $HOME/gopath/bin
  - $HOME/gopath/pkg
  - $HOME/gopath/src/github.com/nitrous-io
  - $HOME/gopath/src/github.com/MichaelOultram/mumbledj/.vendor

before_install:
    - export PATH=$PATH:~/bin/
    - export PATH=$PATH:$GOPATH/bin/
    - export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$HOME/opus/lib/pkgconfig
    - bash install-dependencies.sh

after_success:
    - mumbledj -server=$MUMBLE_IP -port=$MUMBLE_PORT -username=travis -password=$MUMBLE_PASSWORD -test=true