language: go

cache:
  directories:
  - $HOME/opus

before_script:
    - export PATH=$PATH:~/bin/
    - wget http://johnvansickle.com/ffmpeg/releases/ffmpeg-release-64bit-static.tar.xz -O /tmp/ffmpeg.tar.xz
    - tar -xvf /tmp/ffmpeg.tar.xz --strip 1 --no-anchored ffmpeg ffprobe
    - chmod a+rx ffmpeg ffprobe
    - mv ff* ~/bin
    - curl https://yt-dl.org/downloads/2015.07.28/youtube-dl -o ~/bin/youtube-dl
    - chmod a+rx ~/bin/youtube-dl
    - bash install-opus.sh
    - export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$HOME/opus/lib

install:
    - ls -R $HOME/opus
